import React, { createContext, useEffect, useState } from 'react';

export const LanguageContext = createContext();

const translations = {
  en: {
    home: 'Home',
    books: 'Books',
    about: 'About',
    blogs: 'Blogs',
    contact: 'Contact',
    register: 'Register',
    logout: 'Logout',
    menu: 'Menu',
    confirmLogout: 'Confirm Logout',
    logoutMessage: 'Are you sure you want to log out?',
    cancel: 'Cancel',
    welcome: 'Welcome to...',
    lankaReads: 'Lanka Reads',
    beReader: 'Be a Reader',
    beAuthor: 'Be an Author',
    heroDescription: 'Lanka Reads is the best and most popular online bookshop in Sri Lanka. It offers a wide range of digital books for avid readers.',
    authorQuestion: 'Do you want to become an author?',
    yes: 'Yes',
    no: 'No',
    registerHere: 'Register Here',
    name: 'Name',
    enterName: 'Enter your name',
    emailAddress: 'Email address',
    enterEmail: 'Enter your email',
    password: 'Password',
    createPassword: 'Create a password',
    confirmPassword: 'Confirm Password',
    confirmPasswordPlaceholder: 'Confirm your password',
    orRegisterWith: 'or register with',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    login: 'Login',
    loginPlaceholder: 'Enter your password',
    dontHaveAccount: "Don't have an account?",
    registerHere2: 'Register here',
    welcomeBack: 'Welcome back, {name}!',
    loggedInAs: 'You are logged in as {email}.',
    socialText: 'Get connected with us on social networks:',
    ourLinks: 'Our Links',
    resources: 'Resources',
    getInTouch: 'Get in Touch',
    shop: 'Shop',
    authors: 'Authors',
    download: 'Download',
    helpCenter: 'Help Center',
    shoppingCart: 'Shopping Cart',
    partner: 'Partner',
    copyright: '© 2024 Copyright:',
    errors: {
      passwordMismatch: 'Passwords do not match',
      registrationFailed: 'Registration failed. Try again.',
      loginFailed: 'Login failed. Check your credentials.'
    }
  },
  si: {
    home: 'මුල් පිටුව',
    books: 'පොත්',
    about: 'අපි ගැන',
    blogs: 'බ්ලොග්',
    contact: 'සම්බන්ධ වන්න',
    register: 'ලියාපදිංචි වන්න',
    logout: 'ලොග් අවුට්',
    menu: 'මෙනුව',
    confirmLogout: 'ලොග් අවුට් වීම තහවුරු කරන්න',
    logoutMessage: 'ඔබට සැබවින්ම ලොග් අවුට් වීමට අවශ්‍යද?',
    cancel: 'අවලංගු කරන්න',
    welcome: 'සාදරයෙන් පිළිගනිමු...',
    lankaReads: 'ලංකා රීඩ්ස්',
    beReader: 'ක්‍රියාකාරී පාඨකයෙකු වන්න',
    beAuthor: 'කතුවෙකු වන්න',
    heroDescription: 'ලංකා රීඩ්ස් යනු ශ්‍රී ලංකාවේ වඩාත් ජනප්‍රිය සහ හොඳම මාර්ගගත පොත් සාප්පු කඩයක් වන අතර එය කැමති පාඨකයින්ට බොහෝ දුරට ඩිජිටල් පොත් සපයයි.',
    authorQuestion: 'ඔබ කතුවෙකු වීමට කැමතිද?',
    yes: 'ඔව්',
    no: 'නැහැ',
    registerHere: 'මෙතන ලියාපදිංචි වන්න',
    name: 'නම',
    enterName: 'ඔබේ නම ඇතුළත් කරන්න',
    emailAddress: 'ඊමේල් ලිපිනය',
    enterEmail: 'ඔබේ ඊමේල් ලිපිනය ඇතුළත් කරන්න',
    password: 'මුරපදය',
    createPassword: 'මුරපදයක් සාදන්න',
    confirmPassword: 'මුරපදය තහවුරු කරන්න',
    confirmPasswordPlaceholder: 'ඔබේ මුරපදය තහවුරු කරන්න',
    orRegisterWith: 'හෝ මේවා සමඟ ලියාපදිංචි වන්න',
    alreadyHaveAccount: 'දැනටමත් ගිණුමක් තිබේද?',
    loginHere: 'මෙතැනින් පිවිසෙන්න',
    login: 'පිවිසෙන්න',
    loginPlaceholder: 'ඔබේ මුරපදය ඇතුළත් කරන්න',
    dontHaveAccount: 'ගිණුමක් නැද්ද?',
    registerHere2: 'මෙතැනින් ලියාපදිංචි වන්න',
    welcomeBack: 'ආපසු සාදරයෙන් පිළිගනිමු, {name}!',
    loggedInAs: 'ඔබ {email} ලෙස පිවිසී ඇත.',
    socialText: 'සමාජ ජාල මත අප හා සම්බන්ධ වන්න:',
    ourLinks: 'අපගේ සබැඳි',
    resources: 'සම්පත්',
    getInTouch: 'අප හා සම්බන්ධ වන්න',
    shop: 'සාප්පුව',
    authors: 'කතුන්',
    download: 'බාගත කරන්න',
    helpCenter: 'උපකාර මධ්‍යස්ථානය',
    shoppingCart: 'සාප්පු කාට්',
    partner: 'හවුල්කරුවා',
    copyright: '© 2024 ප්‍රකාශන හිමිකම:',
    errors: {
      passwordMismatch: 'මුරපද නොගැළපේ',
      registrationFailed: 'ලියාපදිංචිය අසාර්ථකයි. නැවත උත්සාහ කරන්න.',
      loginFailed: 'පිවිසුම අසාර්ථකයි. වැළඳගැනීම් පරීක්ෂා කරන්න.'
    }
  },
  ta: {
    home: 'முகப்பு',
    books: 'புத்தகங்கள்',
    about: 'எங்களைப் பற்றி',
    blogs: 'வலைப்பதிவுகள்',
    contact: 'தொடர்பு',
    register: 'பதிவு செய்யவும்',
    logout: 'வெளியேறு',
    menu: 'மெனு',
    confirmLogout: 'வெளியேறுவதை உறுதிப்படுத்தவும்',
    logoutMessage: 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
    cancel: 'ரத்துசெய்',
    welcome: 'வரவேற்கிறோம்...',
    lankaReads: 'லங்கா ரீட்ஸ்',
    beReader: 'ஒரு வாசகராகுங்கள்',
    beAuthor: 'ஒரு ஆசிரியராகுங்கள்',
    heroDescription: 'லங்கா ரீட்ஸ் என்பது இலங்கையின் சிறந்த மற்றும் மிகவும் பிரபலமான ஆன்லைன் புத்தகக்கடையாகும். இது ஆர்வமுள்ள வாசகர்களுக்கு பரந்த அளவிலான டிஜிட்டல் புத்தகங்களை வழங்குகிறது.',
    authorQuestion: 'நீங்கள் ஆசிரியராக மாற விரும்புகிறீர்களா?',
    yes: 'ஆம்',
    no: 'இல்லை',
    registerHere: 'இங்கே பதிவு செய்யவும்',
    name: 'பெயர்',
    enterName: 'உங்கள் பெயரை உள்ளிடவும்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    enterEmail: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    password: 'கடவுச்சொல்',
    createPassword: 'கடவுச்சொல்லை உருவாக்கவும்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    confirmPasswordPlaceholder: 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    orRegisterWith: 'அல்லது இதனுடன் பதிவு செய்யவும்',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    loginHere: 'இங்கே உள்நுழையவும்',
    login: 'உள்நுழை',
    loginPlaceholder: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    dontHaveAccount: 'கணக்கு இல்லை எனில்?',
    registerHere2: 'இங்கே பதிவு செய்யவும்',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம், {name}!',
    loggedInAs: 'நீங்கள் {email} ஆக உள்நுழைந்துள்ளீர்கள்.',
    socialText: 'சமூக வலைப்பின்னல்களில் எங்களை இணைக்கவும்:',
    ourLinks: 'எங்கள் இணைப்புகள்',
    resources: 'வளங்கள்',
    getInTouch: 'எங்களைத் தொடர்பு கொள்ளுங்கள்',
    shop: 'கடை',
    authors: 'ஆசிரியர்கள்',
    download: 'பதிவிறக்கவும்',
    helpCenter: 'உதவி மையம்',
    shoppingCart: 'வாங்கும் பட்டியல்',
    partner: 'பங்காளி',
    copyright: '© 2024 பதிப்புரிமை:',
    errors: {
      passwordMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
      registrationFailed: 'பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
      loginFailed: 'உள்நுழைவு தோல்வியடைந்தது. விவரங்களை சரிபார்க்கவும்.'
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('appLanguage') || 'en');

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
  }, [language]);

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
